services:
  - type: pserv
    name: vlf-database
    runtime: postgres
    postgresMajorVersion: 15
    plan: free

  - type: web
    name: vlf-api
    runtime: docker
    dockerfilePath: ./packages/api/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: vlf-database
          property: connectionString